# CI Base Image for HAF development and testing
# Based on hive/ci-base-image (AlmaLinux 8 / manylinux_2_28)
# Extends it with HAF-specific build dependencies
#
# Build:
#   docker build -f Dockerfile.ci-base-image \
#     --build-arg HIVE_CI_IMAGE=registry.gitlab.syncad.com/hive/hive/ci-base-image:<tag> \
#     -t registry.gitlab.syncad.com/hive/haf/ci-base-image:<tag> .

ARG HIVE_CI_IMAGE=registry.gitlab.syncad.com/hive/common-ci-configuration/ci-base-image:fddc56669a22b53e6d75a6d697ee8a0f42a7ce52
ARG POSTGRES_VERSION=18

FROM ${HIVE_CI_IMAGE}

ARG POSTGRES_VERSION
ENV POSTGRES_VERSION=${POSTGRES_VERSION}

SHELL ["/bin/bash", "-c"]

USER root
WORKDIR /usr/local/src

# Build pg_cron
RUN git clone --depth 1 https://github.com/citusdata/pg_cron.git /tmp/pg_cron && \
    cd /tmp/pg_cron && \
    make PG_CONFIG=/usr/pgsql-${POSTGRES_VERSION}/bin/pg_config \
         CFLAGS="-O2 -fPIC -fvisibility=hidden -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough" && \
    make install PG_CONFIG=/usr/pgsql-${POSTGRES_VERSION}/bin/pg_config && \
    rm -rf /tmp/pg_cron

# Install tox and AI packages
RUN pip3 install --break-system-packages tox tokenizers pysbd base58

# Make libpq findable by CMake
RUN ln -sf /usr/pgsql-${POSTGRES_VERSION}/lib/libpq.so /usr/lib64/libpq.so && \
    ln -sf /usr/pgsql-${POSTGRES_VERSION}/lib/libpq.so.5 /usr/lib64/libpq.so.5 && \
    ln -sf /usr/pgsql-${POSTGRES_VERSION}/include /usr/include/postgresql

# Rebuild libpqxx with C++20 and std::source_location support
RUN git clone --depth 1 --branch 7.8.1 https://github.com/jtv/libpqxx.git /tmp/libpqxx && \
    cd /tmp/libpqxx && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DBUILD_TEST=OFF \
          -DCMAKE_CXX_STANDARD=20 \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_INSTALL_LIBDIR=lib64 \
          .. && \
    ninja install && \
    cd / && rm -rf /tmp/libpqxx

# Provide pg_lsclusters stub for AlmaLinux
RUN printf "#!/bin/bash\necho \"${POSTGRES_VERSION} main 5432 online\"\n" > /usr/local/bin/pg_lsclusters && \
    chmod +x /usr/local/bin/pg_lsclusters

# Create haf_maintainer service account
RUN useradd -r -s /usr/sbin/nologin -b /nonexistent \
        -c "HAF maintenance service account" -U haf_maintainer

USER hived