ARG PYTHON_VERSION=3.12-24.04_stable

FROM ubuntu:24.04 AS python_dev

# renovate: datasource=pypi depName=poetry versioning=semver
ARG POETRY_VERSION=2.1.3
ENV POETRY_VERSION=${POETRY_VERSION}
ENV APT_CACHE_DIR=/var/cache/buildkit/apt

RUN --mount=type=cache,mode=0777,sharing=locked,target=${APT_CACHE_DIR} \
    apt-get update && \
    apt-get install -y wget git bash sudo python3.12 python3.12-venv python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m venv --system-site-packages /python_venv && \
    mkdir -vp /packages_to_install && cd /packages_to_install && \
    cp -v /usr/bin/dpkg* \
          /usr/bin/tar \
          /usr/bin/rm \
          /usr/bin/diff \
          /usr/bin/grep \
          /usr/sbin/ldconfig \
          /usr/sbin/start-stop-daemon \
          \
          /lib/x86_64-linux-gnu/libzstd.so.1 \
          /lib/x86_64-linux-gnu/liblzma.so.5 \
          /lib/x86_64-linux-gnu/libbz2.so.1.0 \
          /lib/x86_64-linux-gnu/libselinux.so.1 \
          /lib/x86_64-linux-gnu/libacl.so.1 \
          . \
    && \
    wget \
      http://launchpadlibrarian.net/742374370/dpkg_1.22.11ubuntu1_amd64.deb \
      https://launchpad.net/ubuntu/+source/perl/5.38.2-5/+build/28504793/+files/perl-base_5.38.2-5_amd64.deb \
      https://launchpad.net/ubuntu/+source/debconf/1.5.86ubuntu1/+build/28052301/+files/debconf_1.5.86ubuntu1_all.deb \
      https://launchpad.net/ubuntu/+source/sudo/1.9.15p5-3ubuntu5/+build/28035899/+files/sudo_1.9.15p5-3ubuntu5_amd64.deb \
      http://launchpadlibrarian.net/743048427/coreutils_9.4-3.1ubuntu1_amd64.deb \
      https://launchpad.net/ubuntu/+source/apparmor/4.1.0~beta1-0ubuntu3/+build/29135383/+files/libapparmor1_4.1.0~beta1-0ubuntu3_amd64.deb \
      http://archive.ubuntu.com/ubuntu/pool/main/p/pam/libpam0g_1.5.3-5ubuntu5.4_amd64.deb \
      https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/30939880/+files/libpam-modules_1.5.3-5ubuntu5.4_amd64.deb \
      https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/30939880/+files/libpam-modules-bin_1.5.3-5ubuntu5.4_amd64.deb \
      https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/30939880/+files/libpam-runtime_1.5.3-5ubuntu5.4_all.deb \
      https://launchpad.net/ubuntu/+source/apparmor/4.1.0~beta1-0ubuntu3/+build/29135383/+files/libpam-apparmor_4.1.0~beta1-0ubuntu3_amd64.deb

SHELL ["/bin/bash", "-c"]

RUN set -ex; python3 -m venv --system-site-packages /poetry_venv && \
    source /poetry_venv/bin/activate && \
    pip install --no-cache-dir poetry==$POETRY_VERSION

FROM ubuntu:24.04 AS python_u24_runtime

USER 0:0
RUN apt-get update && \
    apt-get install  --no-install-recommends -y python3.12 python3.12-venv python3-pip  && \
    apt-get clean && rm -r /var/lib/apt/lists/*

# Copy initial set of tools just to be able to add regular root user and group


SHELL ["/bin/bash", "-c"]


ENV PYTHON_VENV_PATH="/python_venv"
ENV PATH="${PYTHON_VENV_PATH}/bin:/packages_to_install/:$PATH" VIRTUAL_ENV=${PYTHON_VENV_PATH}

COPY --from=python_dev \
  /python_venv \
  "${PYTHON_VENV_PATH}"

COPY --from=python_dev /packages_to_install /packages_to_install


# Compile so __pycache__ will be already created for standard Python modules
# Will work similar as e.g. `python -m compileall /urs/lib/python3.12` but is more flexible
RUN python3 -c "import sysconfig, compileall; compileall.compile_dir(sysconfig.get_path('stdlib'))"
