# syntax=docker/dockerfile:1.4
FROM python:3.11.0-alpine3.17

RUN <<-EOF 
  # Install system dependencies
  apk add --no-cache bash git curl gcc g++

  # Install Python dependencies
  pip3 install tox
EOF

CMD ["/bin/bash"]