# To workaround a gitlab healthcheck bug, expose just single port. 
# See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29130#note_1028331564 and
# https://gitlab.com/search?search=Service+docker+dind+probably+didn%27t+start+properly&nav_source=navbar&project_id=250833&group_id=9970&scope=issues&sort=updated_desc
FROM docker:20.10.21-dind as upstream

FROM scratch

COPY --from=upstream / /

VOLUME /var/lib/docker
EXPOSE 2376/tcp

ENTRYPOINT ["dockerd-entrypoint.sh"]
CMD []