# syntax=docker/dockerfile:1.4
FROM docker:26.1.4-cli AS docker-builder

RUN apk add --no-cache bash git coreutils ca-certificates curl sudo
RUN <<EOF
    set -e
    adduser -D hived
    echo "hived ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
EOF
USER hived
WORKDIR /home/hived
