ARG PYTHON_VERSION=3.14-26.04_stable

FROM ubuntu:26.04 AS python_dev

# renovate: datasource=pypi depName=poetry versioning=semver
ARG POETRY_VERSION=2.1.3
ENV POETRY_VERSION=${POETRY_VERSION}
ENV APT_CACHE_DIR=/var/cache/buildkit/apt

RUN --mount=type=cache,mode=0777,sharing=locked,target=${APT_CACHE_DIR} \
    apt-get update && \
    apt-get install -y wget git bash sudo python3.14 python3.14-venv python3-pip && \
    python3 -m venv --system-site-packages /python_venv && \
    mkdir -vp /packages_to_install && cd /packages_to_install && \
    cp -v /usr/bin/dpkg* \
          /usr/bin/tar \
          /usr/bin/rm \
          /usr/bin/diff \
          /usr/bin/grep \
          /usr/sbin/ldconfig \
          /usr/sbin/start-stop-daemon \
          \
          /lib/x86_64-linux-gnu/libzstd.so.1 \
          /lib/x86_64-linux-gnu/liblzma.so.5 \
          /lib/x86_64-linux-gnu/libbz2.so.1.0 \
          /lib/x86_64-linux-gnu/libselinux.so.1 \
          /lib/x86_64-linux-gnu/libacl.so.1 \
          . \
    && \
    # Download the bootstrap packages for the runtime stage from the archive of
    # the release we are building on (replaces the old hardcoded launchpad URLs)
    apt-get download \
      dpkg \
      perl-base \
      debconf \
      sudo \
      sudo-common \
      coreutils \
      coreutils-from-uutils \
      rust-coreutils \
      libapparmor1 \
      libpam0g \
      libpam-modules \
      libpam-modules-bin \
      libpam-runtime \
      libpam-apparmor \
      # pam_limits.so links libsystemd on 26.04 (pam >= 1.7)
      libsystemd0 \
      libcap2 \
      liblz4-1 \
      liblzma5 \
      libzstd1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN set -ex; python3 -m venv --system-site-packages /poetry_venv && \
    source /poetry_venv/bin/activate && \
    pip install --no-cache-dir poetry==$POETRY_VERSION

FROM ubuntu/python:${PYTHON_VERSION} AS python_u26_runtime

USER 0:0

# Copy initial set of tools just to be able to add regular root user and group

COPY --from=python_dev /bin/bash \
  /bin/ls \
  /bin/ln \
  /bin/chown \
  /bin/chmod \
  /bin/whoami \
  /bin/

SHELL ["/bin/bash", "-c"]

COPY --from=python_dev \
  /usr/sbin/useradd \
  /usr/sbin/usermod \
  /usr/sbin/groupadd \
  \
  /usr/sbin/

COPY --from=python_dev \
  /usr/bin/mkdir \
  /usr/bin/dirname \
  /usr/bin/basename \
  /usr/bin/id \
  \
  /usr/bin/

COPY --from=python_dev \
  /lib/x86_64-linux-gnu/libmd.so.0 \
  /lib/x86_64-linux-gnu/libselinux.so.1 \
  /lib/x86_64-linux-gnu/libpcre2-8.so.0 \
  /lib/x86_64-linux-gnu/libcap-ng.so.0 \
  /lib/x86_64-linux-gnu/libsemanage.so.2 \
  /lib/x86_64-linux-gnu/libsepol.so.2 \
  /lib/x86_64-linux-gnu/libaudit.so.1 \
  /lib/x86_64-linux-gnu/libacl.so.1 \
  /lib/x86_64-linux-gnu/libbz2.so.1.0 \
  /lib/x86_64-linux-gnu/


ENV PYTHON_VENV_PATH="/python_venv"
ENV PATH="${PYTHON_VENV_PATH}/bin:/packages_to_install/:$PATH" VIRTUAL_ENV=${PYTHON_VENV_PATH}

COPY --from=python_dev \
  /python_venv \
  "${PYTHON_VENV_PATH}"

COPY --from=python_dev /packages_to_install /packages_to_install

RUN ln -sf /bin/bash /bin/sh && \
  groupadd users && \
  useradd -r -U -o -d /root -ms /bin/bash -u 0 -c "root account" "root" && \
  mkdir -vp /root && chown -R root:root /root && \
  \
  export LD_LIBRARY_PATH="/packages_to_install/:$LD_LIBRARY_PATH" && \
  export DEBIAN_FRONTEND=noninteractive && \
  pushd /packages_to_install && \
  dpkg --force-depends  -i \
    dpkg_*.deb \
    perl-base_*.deb \
    debconf_*.deb \
    libpam0g_*.deb \
    libpam-modules-bin_*.deb \
    libpam-modules_*.deb \
    libpam-runtime_*.deb \
    libapparmor1_*.deb \
    libpam-apparmor_*.deb \
    libsystemd0_*.deb \
    libcap2_*.deb \
    liblz4-1_*.deb \
    liblzma5_*.deb \
    libzstd1_*.deb \
    rust-coreutils_*.deb \
    coreutils-from-uutils_*.deb \
    coreutils_*.deb \
    sudo-common_*.deb \
    sudo_*.deb \
    && \
    dpkg --force-remove-essential --purge \
       perl-base \
       dpkg && \
  rm -rf /var/lib/dpkg/ \
         /packages_to_install && \
  popd

# Compile so __pycache__ will be already created for standard Python modules
# Will work similar as e.g. `python -m compileall /usr/lib/python3.14` but is more flexible
RUN python3 -c "import sysconfig, compileall; compileall.compile_dir(sysconfig.get_path('stdlib'))"
